### ISSUE TITLE
Strange re-direct at login

### ISSUE THREAD

**Issue by ovesemart** [SUNET/eduid-IdP#117] opened 2020-09-16 10:17 UTC
Sometimes we get re-directed back to start page after pressing log in button at log in page.
See attached files in slack-channel, could not add .har files here.

**Comment by fredrikt** [comment] 2020-10-02 14:01
This was caused by sessions being overwritten when requests were sent in parallel. It is fixed in staging now.

**Closed by fredrikt** 2020-10-02 14:01 UTC
